#!/usr/bin/env python3
"""Generate docs/commands.md and docs/README.md. Never edit those files by hand.

- docs/commands.md comes from `asc --experimental-dump-help`, so it is exactly
  what the binary accepts. Fix a description by editing its `help:` string.
- docs/README.md comes from each feature doc's frontmatter `description`.

Usage: scripts/gen-docs.py <path-to-asc-binary>   (normally via `make docs`)
"""
import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
GLOBAL = {"output", "pretty", "timeout"}
SKIP = {"help"}  # the auto-generated help subcommand
GUIDES = [
    ("release.md", "Release workflow"),
    ("library.md", "Use as a Swift package"),
    ("design.md", "Design: CAEOAS and architecture"),
    ("documentation-design/README.md", "How these docs are organised"),
]


def flag_name(arg):
    name = arg["preferredName"]
    return ("-" if name["kind"] == "short" else "--") + name["name"]


def usage_part(arg):
    if arg["kind"] == "positional":
        part = f"<{arg['valueName']}>"
    elif arg["kind"] == "flag":
        part = flag_name(arg)
    else:
        part = f"{flag_name(arg)} <{arg['valueName']}>"
    if arg.get("isRepeating"):
        part += " …"
    return f"[{part}]" if arg.get("isOptional") else part


def is_builtin(arg):
    """ArgumentParser's own --help / --version flags, and the global options."""
    if arg["kind"] == "positional":
        return False
    name = arg["preferredName"]["name"]
    if name == "help" or name in GLOBAL:
        return True
    return name == "version" and arg["kind"] == "flag" and arg.get("abstract") == "Show the version."


def args_of(cmd):
    return [a for a in cmd.get("arguments", []) if a.get("shouldDisplay", True) and not is_builtin(a)]


def cell(text):
    return (text or "").replace("|", "\\|").replace("\n", " ")


def render_command(path, cmd, out, heading=True):
    args = args_of(cmd)
    if heading:
        out += [f"### {' '.join(path)}", ""]
        if cmd.get("abstract"):
            out += [cell(cmd["abstract"]), ""]
    required = [usage_part(a) for a in args if not a.get("isOptional")]
    optional = [usage_part(a) for a in args if a.get("isOptional")]
    out += ["```", " ".join(path + required + optional), "```", ""]
    if args:
        out += ["| Flag | Required | Default | Description |", "|---|---|---|---|"]
        for a in args:
            name = f"<{a['valueName']}>" if a["kind"] == "positional" else flag_name(a)
            desc = cell(a.get("abstract"))
            if a.get("allValues"):
                desc += f" One of: {', '.join(a['allValues'])}."
            default = f"`{a['defaultValue']}`" if a.get("defaultValue") else ""
            out.append(f"| `{name}` | {'' if a.get('isOptional') else 'yes'} | {default} | {desc.strip()} |")
        out.append("")


def visible_subs(cmd):
    return [s for s in cmd.get("subcommands", []) if s.get("shouldDisplay", True) and s["commandName"] not in SKIP]


def walk(path, cmd, out, top=False):
    subs = visible_subs(cmd)
    if not subs:
        render_command(path, cmd, out, heading=not top)
    for sub in subs:
        walk(path + [sub["commandName"]], sub, out)


def gen_commands(binary):
    env = dict(os.environ, ASC_NO_PLUGINS="1")
    dump = json.loads(subprocess.run([binary, "--experimental-dump-help"], env=env,
                                     capture_output=True, text=True, check=True).stdout)
    root = dump["command"]
    top = [s for s in root["subcommands"] if s.get("shouldDisplay", True) and s["commandName"] not in SKIP]
    out = [
        "<!-- GENERATED by `make docs` from `asc --experimental-dump-help`. Do not edit. -->",
        "# Command reference",
        "",
        "Every `asc` command and flag, generated from the binary. For how to use a feature, start at the [docs index](README.md).",
        "",
        "**Global flags** (accepted by every command, not repeated below):",
        "`--output json|table|markdown` (default `json`) · `--pretty` · `--timeout <30s|2m>`",
        "",
        "**Commands:** " + " · ".join(f"[{s['commandName']}](#asc-{s['commandName']})" for s in top),
        "",
    ]
    for sub in top:
        out += [f"## asc {sub['commandName']}", ""]
        if sub.get("abstract"):
            out += [cell(sub["abstract"]), ""]
        walk(["asc", sub["commandName"]], sub, out, top=True)
    (DOCS / "commands.md").write_text("\n".join(out).rstrip() + "\n")


def description(path):
    text = path.read_text()
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if m and (d := re.search(r"^description:\s*(.+)$", m.group(1), re.M)):
        return d.group(1).strip()
    return ""


def gen_index():
    features = DOCS / "features"
    docs = sorted(features.glob("*/README.md"), key=lambda p: p.parent.name)
    docs += sorted(p for p in features.glob("*.md"))
    rows = []
    for p in sorted(docs, key=lambda p: p.parent.name if p.name == "README.md" else p.stem):
        name = p.parent.name if p.name == "README.md" else p.stem
        rows.append(f"| [{name}]({p.relative_to(DOCS).as_posix()}) | {cell(description(p))} |")
    guides = [f"[{title}]({f})" for f, title in GUIDES if (DOCS / f).exists()]
    out = [
        "<!-- GENERATED by `make docs` from docs/features/*/README.md frontmatter. Do not edit. -->",
        "# asc-cli docs",
        "",
        "New here? Start with the [README](../README.md). For every flag, see the [command reference](commands.md).",
        "",
        "| Feature | What it's for |",
        "|---|---|",
        *rows,
        "",
        "**Guides:** " + " · ".join(guides),
        "",
    ]
    (DOCS / "README.md").write_text("\n".join(out))


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    gen_commands(sys.argv[1])
    gen_index()


if __name__ == "__main__":
    main()
